### ISSUE TITLE
Apparently, the 404s or errors are being cached

### ISSUE THREAD

**Issue by oskosk** [CGastrell/express-tile-cache#5]

**Comment by CGastrell** [comment]
can you provide some sample tms service/url to test? I has a candidate but need more testing

**Comment by oskosk** [comment]
The request for an uncached tile is being piped directly to `res`. An error on the stream should be checked. 

Given that, take in account that `superagent` does not emit an error an it does not set `err` on the callback parameter if it got a valid HTTP Status (Even if it was a `404`, or a `503`, a `500` or a `401`). An HTTP status from a working server is not considered en error in superagent. 

So, currently, responses from 404 or 503 errors are being cached

https://github.com/CGastrell/express-tile-cache/blob/master/lib/index.js#L66

**Comment by CGastrell** [comment]
Proposed fix will remove superagent dependency moving to Mikeal request module. Response still gets piped, but a response listener will be in charge of checking res.statusCode >= 300 for validating cache routines. Still needs testing. Care for a sample url? Tested against ign.gob.ar TMS requesting a bogus layer(group):

/tms/1.0.0/nonexistentLayerGroup/4/5/6.png

Geoserver handles a proper response (non empty) with a statusCode set to 400. This sample passed the test. I was just hoping to do further testing prior to release.

**Comment by CGastrell** [comment]
Implemented proposed solution on v1.3.2, closing issue till further notice
