### ISSUE TITLE
Streaming to http response and cache at the same time results in both hanging

### ISSUE THREAD

**Issue by chriswhong** [CGastrell/express-tile-cache#9]
https://github.com/CGastrell/express-tile-cache/blob/master/lib/index.js#L119

piping to `res` while sending `resp` to the file store results in both streams hanging (at least for me).  It never finishes writing the file to the cache, and the image I get back in the browser is some percentage of the whole (sometimes it gets farther than others)

This talks about piping to multiple streams where one is requesting data faster than the other.  Will try to implement a workaround and PR it.
http://stackoverflow.com/questions/19553837/node-js-piping-the-same-stream-into-multiple-writable-targets

**Comment by CGastrell** [comment]
I have to find a better solution so it doesn't break compatibility with s3-tile-storage (which is one of the components that brings HA solution to this tile cache).

I think I could return the details and the stream back to the controlling script like:

``` javascript
callback(null, details, fs.createReadStream(details.location));
```

So the s3-tile-storage version would be:

``` javascript
callback(null, details, request(details.location));
```

**Comment by chriswhong** [comment]
I defer to you on the best way to implement, i don't know what I don't
know.  I'll happily test it when it's complete.

**Comment by CGastrell** [comment]
right! thanks!
